---
- name: Install Docker on Alma Linux 9
  hosts: all
  become: true

  tasks:
  - name: Add Docker repository
    yum_repository:
      name: docker-ce
      description: docker-ce repo
      baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
      gpgkey: https://download.docker.com/linux/centos/gpg
      gpgcheck: yes

  # - name: Install required packages
  #   dnf:
  #     name: "{{ item }}"
  #     state: present
  #     update_cache: true
  #   with_items:
  #     - dnf-plugins-core
  #     - container-selinux
  #     - yum-utils
  #     - device-mapper-persistent-data
  #     - lvm2

  - name: Uninstall Podman and Buildah
    dnf:
      name: "{{ item }}"
      state: absent
    with_items:
      - podman
      - buildah

  - name: Install Docker
    dnf:
      name: docker-ce
      state: present
      update_cache: true

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Add steven to docker group
    user:
      name: steven
      groups: docker
      append: yes

  - name: Unconditionally reboot the machine with all defaults
    become: yes
    ansible.builtin.reboot: