---
- hosts: all
  tasks:
  - name: Install utils
    become: yes
    ansible.builtin.dnf:
      name:
        - vim
        - tmux
        - git
        - "@Development Tools"

  - name: Git checkout dotfiles repo
    ansible.builtin.git:
      repo: 'https://github.com/stevester94/dotfiles.git'
      dest: /home/steven/dotfiles