---
- hosts: all
  become: yes
  tasks:
  - name: disable wayland in gnome (superfluous?)
    lineinfile:
      path: /etc/gdm/custom.conf
      regexp: '#WaylandEnable=false'
      line: 'WaylandEnable=false'
      backup: yes

  - name: Install a list of packages
    become: yes
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - "epel-release"
      - "@base-x"
      - "@Xfce"
      - xrdp
      - mock

  - name: Add steven to mock group
    user:
      name: steven
      groups: mock
      append: yes

  - name: Enable and start xrdp service
    service:
      name: xrdp
      state: started
      enabled: yes

  - name: permit xrdp traffic
    ansible.posix.firewalld:
      port: 3389/tcp
      permanent: true
      state: enabled